# Dependabot configurtion for .NET Core dependencies

version: 2
updates:

  # maintain dependencies for NuGet
  - package-ecosystem: "nuget"
    directory: "/Project0"
    schedule:
      interval: "daily"
